# Generated by Django 5.1 on 2024-08-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Recommendation date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='my_app.book')),
                ('reasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='my_app.book')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
