# Generated by Django 5.1 on 2024-08-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='reasons',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommends',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book'),
        ),
    ]
