# Generated by Django 5.1 on 2024-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_recommendation_reasons_recommendation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=250)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(verbose_name='Review date')),
            ],
        ),
    ]
