# Generated by Django 5.1 on 2024-08-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(related_name='books', to='my_app.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='my_app.book'),
        ),
    ]
